rr:
	gcc round_robin.c -o round_robin && ./round_robin < processes.txt && rm -f round_robin
fcfs:
	gcc FCFS.c -o FCFS && ./FCFS < processes.txt && rm -f FCFS
sjf:
	gcc SJF.c -o SJF && ./SJF < processes.txt && rm -f SJF
