#array_header.h and rr_header will both need to be in same directory as the c programs

rr:
	gcc RR.c -o RR && ./RR < processes.txt && rm -f RR
fcfs:
	gcc FCFS.c -o FCFS && ./FCFS < processes.txt && rm -f FCFS
sjf:
	gcc SJF.c -o SJF && ./SJF < processes.txt && rm -f SJF
