
#first line structure is <what you are building>:<its dependancies>
text_editor:text_editor.c 
	$(CC) text_editor.c -o text_editor -Wall -Wextra -pedantic -std=c99 
	#'-Wall' give warnings about imporper code structure
	#'-Wextra' and '-pedantic' are also for structure warnings but not syntax so the flags may run warnings ven if code technically work

	#'-std=c99' specifies we are using c version 99 which allows variables to be declared anywhere while the older 'ANSI C' requires declarations at the top of the code
