test1:
	gcc main.c -lm -o a.out
	./a.out < in1.txt > out.txt
	rm -f a.out
test2:
	gcc main.c  -lm -o a.out
	./a.out < in2.txt > out.txt
	rm -f a.out
test3:
	gcc main.c -lm -o a.out
	./a.out < in3.txt > out.txt
	rm -f a.out