main1:
	gcc main1.c -o main1 -lm && ./main1 < in1.txt > out.txt && rm -f main1
test:
	gcc test.c -o test -lm && ./test && rm -f test

main2:
	gcc main2.c -o main2 -lm && ./main2 < in1.txt > out.txt && rm -f main2